version: '3.9'
services:
  redis-proxy-api:
    image: redis-proxy-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - redis
  redis:
    image: redis
